#:schema https://raw.githubusercontent.com/alphal00p/gammaloop/refs/heads/hedge_numerator/assets/schemas/runhistory.json
commands = [
    "import model scalars-default.json",
    "import amplitude ./scalar_box.dot",
    "generate",
	"quit"
    # "inspect --process-id 0 --name box -m -p 0.1 0.2 0.3",
]

[default_runtime_settings.kinematics.externals]
type = "constant"

[default_runtime_settings.kinematics]
e_cm = 0.2

[default_runtime_settings.kinematics.externals.data]
momenta = [
    [
        0.1,
        0.0,
        0.0,
        0.1,
    ],
    [
        0.1,
        0.0,
        0.0,
        -0.1,
    ],
    [
        0.09903067841547669,
        0.03734458315384239,
        0.06393671561700484,
        -0.0657613394982612,
    ],
]
helicities = [1, 1, 1, 1]

[default_runtime_settings.stability]
rotation_axis = []
check_on_norm = true

[default_runtime_settings.subtraction]
disable_threshold_subtraction = true

[default_runtime_settings.sampling]
type = "default"
mode = "spherical"
mapping = "linear"

[cli_settings.global.generation]
enable_thresholds = false

[cli_settings.global.generation.evaluator]
iterative_orientation_optimization = true
compile = false

[default_runtime_settings.integrator]
seed = 42
n_increase = 0
n_start = 100000
n_max = 1000000
discrete_dim_learning_rate = 1.5
continuous_dim_learning_rate = 1.5
max_prob_ratio = 0.01

[tropnis_settings]
processed_dot_file = "/home/nic/Master/tropnis/gl_files/dot_files/scalar_box_processed.dot"
model_json_file = "/home/nic/Master/tropnis/gl_files/models/scalars.json"